# Dippy Breakers private server config file
# You shouldn't need to touch anything in this file

# Sanic config
CORS_ORIGINS = "*"
CORS_ALWAYS_SEND = "True"
KEEP_ALIVE_TIMEOUT = 300

[server]
host = "127.0.0.1"
port = 80

[content]
# The file path location to serve cooked game PAKs/built chunks from
# The build manifest path should contain all PAK files from a build manifest under the folder /{version}/{platform}/{pak}
# Version being e.g. 1.88.244-r17036752
# Platform being the client platform & texture format e.g. Android_ASTC/IOS/Windows
# Pak being the pak file e.g. pakchunk1_pak1.pak
build-manifest = "D:/Battle Breakers/"
# The ChunkV3 path should contain all the built chunks included within the pak & master manifests under the folder /{changelist}/{platform}/ChunksV3/{DataGroupList}/{ChunkHashGUID}
# Changelist being the version CL e.g. CL_3296092
# Platform being the client platform & texture format e.g. Android_ASTC/IOS/WindowsNoEditor
# DataGroupList being a two digit number 00-99, from the manifest
# ChunkHashGUID being comprised of two parts - HEX_GUID.chunk e.g. 8BEE6A9E10AC85D7_251136F44E4DAE61C3A650B5472D389A.chunk
# Hex being derived from reversing the hash blob after converting to hex
# GUID simply being the GUID of the chunk
chunk-v3 = "D:/Battle Breakers/ChunkV3/"

[database]
uri = "mongodb://localhost:27017"
database = "dippy_battle_breakers"

[calendar]
news = "https://calendar.google.com/calendar/ical/be8092e46747abd9d5f78b73c63388bb18ce4fbdc166fa9f16baa90684678332%40group.calendar.google.com/public/basic.ics"
limited-time-mode = "https://calendar.google.com/calendar/ical/24676ff967991fef6d118e34c8b11c2286de569ec62619a9af90629382cdf32b%40group.calendar.google.com/public/basic.ics"
marketing = "https://calendar.google.com/calendar/ical/d618ed832d566c54cd23b8fca67fd648d15e6588b229574b138624d71ff0ef54%40group.calendar.google.com/public/basic.ics"
rotational-content = "https://calendar.google.com/calendar/ical/b8fa9ca9110798613c3e70027bd561d6b588bd90b74113cff0e9158ea04f82e9%40group.calendar.google.com/public/basic.ics"
featured-stores-mcp = "https://calendar.google.com/calendar/ical/9f05d6a22f16d685f2794d1d4d3f953b58a0bd4d722058760fc6f973cad4a243%40group.calendar.google.com/public/basic.ics"
weekly-challenge = "https://calendar.google.com/calendar/ical/d67afe308646a2dc33dc158cb944706a4ac31cb7ccbb2ea1f76d8fdfe923b890%40group.calendar.google.com/public/basic.ics"
battlepass = "https://calendar.google.com/calendar/ical/7dad99419c9ee8c8d7982ff93108b946ca32248bd9fa95e4518e052dad44c219%40group.calendar.google.com/public/basic.ics"
