# Dippy Breakers private server config file
# You shouldn't need to touch anything in this file

# Sanic config
CORS_ORIGINS = "*"
CORS_ALWAYS_SEND = "True"
KEEP_ALIVE_TIMEOUT = 300

[server]
host = "127.0.0.1"
port = 80

[database]
uri = "mongodb://localhost:27017"
database = "dippy_battle_breakers"

[calendar]
news = "https://calendar.google.com/calendar/ical/be8092e46747abd9d5f78b73c63388bb18ce4fbdc166fa9f16baa90684678332%40group.calendar.google.com/public/basic.ics"
limited-time-mode = "https://calendar.google.com/calendar/ical/24676ff967991fef6d118e34c8b11c2286de569ec62619a9af90629382cdf32b%40group.calendar.google.com/public/basic.ics"
marketing = "https://calendar.google.com/calendar/ical/d618ed832d566c54cd23b8fca67fd648d15e6588b229574b138624d71ff0ef54%40group.calendar.google.com/public/basic.ics"
rotational-content = "https://calendar.google.com/calendar/ical/b8fa9ca9110798613c3e70027bd561d6b588bd90b74113cff0e9158ea04f82e9%40group.calendar.google.com/public/basic.ics"
featured-stores-mcp = "https://calendar.google.com/calendar/ical/9f05d6a22f16d685f2794d1d4d3f953b58a0bd4d722058760fc6f973cad4a243%40group.calendar.google.com/public/basic.ics"
weekly-challenge = "https://calendar.google.com/calendar/ical/d67afe308646a2dc33dc158cb944706a4ac31cb7ccbb2ea1f76d8fdfe923b890%40group.calendar.google.com/public/basic.ics"
battlepass = "https://calendar.google.com/calendar/ical/7dad99419c9ee8c8d7982ff93108b946ca32248bd9fa95e4518e052dad44c219%40group.calendar.google.com/public/basic.ics"
